### ISSUE TITLE
for some ASINS,   library breaks with   error, and not return data.

### ISSUE THREAD

**Issue by ivantalpa** [keepacom/php_api#8]
ASIN: *B00EA0XEMC*
Exception: JSON property "categories" must not be NULL
```
#0 /app/src/vendor/netresearch/jsonmapper/src/JsonMapper.php(353): JsonMapper->map(Object(stdClass), Object(Keepa\objects\Product))
#1 /app/src/vendor/netresearch/jsonmapper/src/JsonMapper.php(243): JsonMapper->mapArray(Array, Array, '\\Keepa\\objects\\...')
#2 /app/src/vendor/keepa/php_api/src/KeepaAPI.php(75): JsonMapper->map(Object(stdClass), Object(Keepa\API\Response))
#3 /app/src/vendor/keepa/php_api/src/KeepaAPI.php(149): Keepa\KeepaAPI->sendRequest(Object(Keepa\API\Request))
```

**Comment by keepacom** [comment]
Hello,

Thanks for reporting ! We solved it in 1.13.1 (832de99416803b3662d8f90e113a39cfc20d015c)
